### ISSUE TITLE
Chunkloader in hand is MASSIVE (v1.1.0)

### ISSUE THREAD

**Issue by Boomflex** [CorwinJV/AChunkLoader#2]
Hey Corwin o/

Just playing with the Chunkloader in Creative and the item in the players hand is crazy big!

https://gyazo.com/759748d7d4e53355b72dbf299f95cfc6

It is a "small" issue (pardon the pun), but an aesthetic one none the less :)

Boom

**Comment by CorwinJV** [comment]
Should be in the latest release
